export interface ApiTool {
  name: string;
  description: string;
  url: string;
  method: string;
  path: string;
  price: string;
  category: string;
  parameters: Record<string, ParameterDef>;
  required?: string[];
}

interface ParameterDef {
  type: string;
  description: string;
  enum?: string[];
}

export const CATALOG: ApiTool[] = [
  {
    name: "hyperliquid_data",
    description: "Hyperliquid perp markets: prices, open interest, 24h volume, orderbook depth for 229 markets",
    url: "https://hyperliquid-data.api.klymax402.com",
    method: "GET",
    path: "/api/orderbook",
    price: "$0.001", category: "hyperliquid",
    parameters: { "coin": { type: "string", description: "Coin symbol (e.g. BTC, ETH, SOL, ARB, DOGE)" } },
    required: ["coin"],
  },
  {
    name: "hyperliquid_whales",
    description: "Track whale positions on Hyperliquid DEX. Top traders, position sizes, PnL, entry prices",
    url: "https://hyperliquid-whales.api.klymax402.com",
    method: "GET",
    path: "/api/positions",
    price: "$0.003", category: "hyperliquid",
    parameters: { "coin": { type: "string", description: "Filter by coin symbol (e.g. BTC, ETH, SOL). Optional — returns all coins if omitted." } },
  },
  {
    name: "hl_vaults",
    description: "Hyperliquid vault summaries: APR, TVL, PnL, depositor count",
    url: "https://hl-vaults.api.klymax402.com",
    method: "GET",
    path: "/api/vaults",
    price: "$0.003", category: "hyperliquid",
    parameters: { "limit": { type: "number", description: "Max vaults to return (default: 20)" } },
  },
  {
    name: "hl_funding",
    description: "Real-time and historical funding rates for 229 Hyperliquid perp markets. Arb scanner",
    url: "https://hl-funding.api.klymax402.com",
    method: "POST",
    path: "/api/rates",
    price: "$0.002", category: "hyperliquid",
    parameters: { "sort": { type: "string", description: "Sort order for funding rates. 'highest' = most positive first (shorts pay longs), 'lowest' = most negative first (longs pay shorts), 'abs' = highest absolute value first (default).", enum: ["highest","lowest","abs"] } },
  },
  {
    name: "hl_portfolio",
    description: "Hyperliquid account analysis: positions, PnL, fills, open orders, funding payments",
    url: "https://hl-portfolio.api.klymax402.com",
    method: "POST",
    path: "/api/account",
    price: "$0.003", category: "hyperliquid",
    parameters: { "address": { type: "string", description: "Hyperliquid wallet address (0x...) to retrieve account state for" } },
    required: ["address"],
  },
  {
    name: "hl_spot",
    description: "Hyperliquid spot markets: 454 tokens, prices, volume, balances",
    url: "https://hl-spot.api.klymax402.com",
    method: "POST",
    path: "/api/tokens",
    price: "$0.002", category: "hyperliquid",
    parameters: { "search": { type: "string", description: "Optional filter: search tokens by name or symbol (case-insensitive substring match). Omit to return all 454 tokens." } },
  },
  {
    name: "prediction_markets",
    description: "Active prediction market events from Polymarket + Kalshi: probabilities, volume, trending",
    url: "https://prediction-markets.api.klymax402.com",
    method: "POST",
    path: "/api/markets",
    price: "$0.005", category: "prediction",
    parameters: { "category": { type: "string", description: "Filter markets by topic category. Omit for all categories.", enum: ["politics","crypto","sports","science","culture"] }, "limit": { type: "number", description: "Number of markets to return (1-50). Default: 20." }, "sort": { type: "string", description: "Sort order. 'volume' = highest traded, 'newest' = recently created, 'closing_soon' = ending soonest. Default: volume.", enum: ["volume","newest","closing_soon"] }, "source": { type: "string", description: "Filter by platform. Omit to get markets from both Polymarket and Kalshi.", enum: ["polymarket","kalshi"] } },
  },
  {
    name: "event_resolver",
    description: "Settlement oracle for prediction markets: resolve outcomes, verify claims, check thresholds",
    url: "https://event-resolver.api.klymax402.com",
    method: "POST",
    path: "/api/resolve",
    price: "$0.005", category: "prediction",
    parameters: { "question": { type: "string", description: "The event question to resolve, e.g. 'Did BTC reach $100K by April 2026?' or 'Did the Lakers win the NBA Finals 2026?'" }, "type": { type: "string", description: "Type of resolution expected. binary = Yes/No, numeric = a number, categorical = one of several options. Default: binary.", enum: ["binary","numeric","categorical"] } },
    required: ["question"],
  },
  {
    name: "wallet_portfolio",
    description: "Multi-chain wallet balances and token holdings",
    url: "https://wallet-portfolio.api.klymax402.com",
    method: "GET",
    path: "/api/portfolio",
    price: "$0.003", category: "crypto",
    parameters: { "address": { type: "string", description: "Wallet address (0x...)" }, "chain": { type: "string", description: "Blockchain network (default: base)", enum: ["base","ethereum"] } },
    required: ["address"],
  },
  {
    name: "gas_oracle",
    description: "Real-time gas prices across EVM chains. Fast/standard/slow estimates",
    url: "https://gas-oracle.api.klymax402.com",
    method: "GET",
    path: "/api/price",
    price: "$0.001", category: "crypto",
    parameters: { "chain": { type: "string", description: "Blockchain network (default: base)", enum: ["base","ethereum"] } },
  },
  {
    name: "gas_estimator",
    description: "Multi-chain gas prices in one call -- ETH, Base, Polygon, Arbitrum, BSC compared",
    url: "https://gas-estimator.api.klymax402.com",
    method: "POST",
    path: "/api/estimate",
    price: "$0.002", category: "crypto",
    parameters: { "chain": { type: "string", description: "Chain name: ethereum, base, polygon, arbitrum, bsc. Omit for all chains." } },
  },
  {
    name: "dex_quotes",
    description: "Best swap quotes across DEXs. Multi-chain aggregation, price impact",
    url: "https://dex-quotes.api.klymax402.com",
    method: "GET",
    path: "/api/quote",
    price: "$0.005", category: "crypto",
    parameters: { "tokenIn": { type: "string", description: "Contract address of input token (e.g. 0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913 for USDC on Base)" }, "tokenOut": { type: "string", description: "Contract address of output token (e.g. 0x4200000000000000000000000000000000000006 for WETH on Base)" }, "amount": { type: "string", description: "Amount of input token in raw units (wei/smallest unit, e.g. 1000000 for 1 USDC)" }, "chain": { type: "string", description: "Blockchain network: base or ethereum (default: base)", enum: ["base","ethereum"] } },
    required: ["tokenIn","tokenOut","amount"],
  },
  {
    name: "token_price",
    description: "Real-time crypto token prices via CoinGecko",
    url: "https://token-price.api.klymax402.com",
    method: "POST",
    path: "/api/price",
    price: "$0.001", category: "crypto",
    parameters: { "token": { type: "string", description: "Token name or CoinGecko ID (e.g. bitcoin, ethereum, solana)" }, "currency": { type: "string", description: "Target currency for price (default: usd). Supports usd, eur, gbp, etc." } },
    required: ["token"],
  },
  {
    name: "defi_yields",
    description: "Best DeFi yields across protocols. APY, TVL, risk scores",
    url: "https://defi-yields.api.klymax402.com",
    method: "GET",
    path: "/api/yields",
    price: "$0.002", category: "crypto",
    parameters: { "token": { type: "string", description: "Token symbol to find yields for (e.g. USDC, ETH, WBTC)" }, "chain": { type: "string", description: "Filter by chain (e.g. base, ethereum, arbitrum, polygon). Optional — returns all chains if omitted." }, "minTvl": { type: "number", description: "Minimum TVL in USD to filter pools (default: 100000)" }, "limit": { type: "number", description: "Number of results to return (default: 10, max: 50)" } },
    required: ["token"],
  },
  {
    name: "whale_alert",
    description: "Track large crypto transactions and whale movements",
    url: "https://whale-alert.api.klymax402.com",
    method: "POST",
    path: "/api/whales",
    price: "$0.003", category: "crypto",
    parameters: { "chain": { type: "string", description: "Blockchain: 'ethereum' or 'base' (default: ethereum)" }, "minValue": { type: "number", description: "Minimum transaction value in ETH (default: 100)" } },
  },
  {
    name: "crypto_news",
    description: "Real-time crypto news with sentiment scores",
    url: "https://crypto-news.api.klymax402.com",
    method: "GET",
    path: "/api/news",
    price: "$0.002", category: "crypto",
    parameters: { "limit": { type: "number", description: "Number of articles to return (default 20, max 100)." }, "token": { type: "string", description: "Filter by token symbol (e.g. BTC, ETH, SOL). Optional — returns all if omitted." } },
  },
  {
    name: "funding_arb",
    description: "Funding rate arbitrage opportunities across exchanges",
    url: "https://funding-arb.api.klymax402.com",
    method: "GET",
    path: "/api/scan",
    price: "$0.005", category: "crypto",
    parameters: { "symbol": { type: "string", description: "Filter by asset symbol (e.g. BTC, ETH, SOL). Optional — scans all assets if omitted." } },
  },
  {
    name: "funding_rates",
    description: "Live perpetual funding rates across Binance, Bybit, OKX with open interest and predicted next rate",
    url: "https://funding-rates.api.klymax402.com",
    method: "GET",
    path: "/api/rates",
    price: "$0.002", category: "crypto",
    parameters: { "symbol": { type: "string", description: "Token symbol (e.g. BTC, ETH, SOL)" } },
    required: ["symbol"],
  },
  {
    name: "ens_resolver",
    description: "Resolve ENS names to addresses and reverse lookup",
    url: "https://ens-resolver.api.klymax402.com",
    method: "POST",
    path: "/api/resolve",
    price: "$0.002", category: "crypto",
    parameters: { "name": { type: "string", description: "ENS name to resolve (e.g. vitalik.eth)" }, "address": { type: "string", description: "Ethereum address for reverse resolution (e.g. 0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045)" } },
  },
  {
    name: "token_holders",
    description: "Token holder distribution: whale count, concentration, top holders",
    url: "https://token-holders.api.klymax402.com",
    method: "GET",
    path: "/api/holders",
    price: "$0.005", category: "crypto",
    parameters: { "address": { type: "string", description: "Token contract address (0x...)" }, "chain": { type: "string", description: "Chain: base, ethereum (default: base)" } },
    required: ["address"],
  },
  {
    name: "token_ohlcv",
    description: "Historical OHLCV candles for any token",
    url: "https://token-ohlcv.api.klymax402.com",
    method: "GET",
    path: "/api/candles",
    price: "$0.002", category: "crypto",
    parameters: { "token": { type: "string", description: "CoinGecko token ID (e.g. bitcoin, ethereum, solana). Use this OR contract+chain." }, "contract": { type: "string", description: "On-chain contract address (e.g. 0x...). Use with chain parameter for GeckoTerminal lookup." }, "chain": { type: "string", description: "Blockchain network for contract lookup: base, ethereum, solana, arbitrum, polygon, optimism, bsc." }, "days": { type: "number", description: "Number of days of history (default 30, max 365). For 1h interval max 2 days, for 4h max 90 days." }, "interval": { type: "string", description: "Candle interval: daily (default), 4h (if days <= 90), 1h (if days <= 2)." } },
  },
  {
    name: "airdrop_checker",
    description: "Check wallet eligibility for active crypto airdrops with token, value, deadline, and claim URL",
    url: "https://airdrop-checker.api.klymax402.com",
    method: "GET",
    path: "/api/check",
    price: "$0.005", category: "crypto",
    parameters: { "address": { type: "string", description: "Ethereum wallet address (0x...)" } },
    required: ["address"],
  },
  {
    name: "bridge_routes",
    description: "Best cross-chain bridge routes via LI.FI -- 60+ chains, 18+ bridges, fees and time compared",
    url: "https://bridge-routes.api.klymax402.com",
    method: "GET",
    path: "/api/route",
    price: "$0.003", category: "crypto",
    parameters: { "fromChain": { type: "string", description: "Source chain ID (1=Ethereum, 8453=Base, 42161=Arbitrum, 10=Optimism, 137=Polygon, 56=BSC, 43114=Avalanche)" }, "toChain": { type: "string", description: "Destination chain ID (1=Ethereum, 8453=Base, 42161=Arbitrum, 10=Optimism, 137=Polygon, 56=BSC, 43114=Avalanche)" }, "token": { type: "string", description: "Token symbol to bridge (e.g. USDC, USDT, ETH, WETH)" }, "amount": { type: "string", description: "Amount in smallest unit (e.g. 1000000 for 1 USDC with 6 decimals, 1000000000000000000 for 1 ETH)" }, "toToken": { type: "string", description: "Destination token symbol if different from source (optional, defaults to same as token)" } },
    required: ["fromChain","toChain","token","amount"],
  },
  {
    name: "currency_converter",
    description: "Real-time fiat (ECB) and crypto (CoinGecko) conversion",
    url: "https://currency-converter.api.klymax402.com",
    method: "POST",
    path: "/api/convert",
    price: "$0.001", category: "crypto",
    parameters: { "amount": { type: "number", description: "Amount to convert" }, "from": { type: "string", description: "Source currency code (e.g., USD, EUR, BTC, ETH)" }, "to": { type: "string", description: "Target currency code (e.g., EUR, GBP, USD, BTC)" } },
    required: ["amount","from","to"],
  },
  {
    name: "base_defi",
    description: "Base chain DeFi yields from Aerodrome LP and Moonwell lending, ranked by APY with TVL and risk",
    url: "https://base-defi.api.klymax402.com",
    method: "GET",
    path: "/api/opportunities",
    price: "$0.003", category: "defi",
    parameters: { "protocol": { type: "string", description: "Filter by protocol: 'all', 'aerodrome', or 'moonwell'. Defaults to 'all'.", enum: ["all","aerodrome","moonwell"] } },
  },
  {
    name: "liquidation_oracle",
    description: "DeFi liquidation levels from Aave, Compound, Morpho -- at-risk positions and price triggers",
    url: "https://liquidation-oracle.api.klymax402.com",
    method: "GET",
    path: "/api/levels",
    price: "$0.003", category: "defi",
    parameters: { "protocol": { type: "string", description: "Filter by protocol (e.g. aave, compound, morpho, venus). Use 'all' or omit for all protocols." }, "asset": { type: "string", description: "Filter by collateral asset symbol (e.g. ETH, WBTC, stETH). Optional — returns all assets if omitted." }, "minValueUsd": { type: "number", description: "Minimum at-risk value in USD to include (default: 10000)" }, "limit": { type: "number", description: "Number of results to return (default: 20, max: 100)" } },
  },
  {
    name: "orderbook_depth",
    description: "Uniswap V3 liquidity depth -- price impact at 1/2/5/10% levels for slippage estimation",
    url: "https://orderbook-depth.api.klymax402.com",
    method: "GET",
    path: "/api/depth",
    price: "$0.005", category: "defi",
    parameters: { "pool": { type: "string", description: "Uniswap V3 pool address (0x...)" }, "chain": { type: "string", description: "Chain name: base, ethereum (default: base)" } },
    required: ["pool"],
  },
  {
    name: "nft_collection",
    description: "NFT collection floor price, volume, holders, and rarity data for Ethereum and Base",
    url: "https://nft-floor.api.klymax402.com",
    method: "GET",
    path: "/api/collection",
    price: "$0.005", category: "nft",
    parameters: { "address": { type: "string", description: "NFT collection contract address. e.g. 0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D (BAYC)" }, "chain": { type: "string", description: "Blockchain: ethereum or base. Default: ethereum" } },
    required: ["address"],
  },
  {
    name: "nft_rarity",
    description: "NFT token rarity rank, score, and trait floor prices for valuation",
    url: "https://nft-floor.api.klymax402.com",
    method: "GET",
    path: "/api/rarity",
    price: "$0.003", category: "nft",
    parameters: { "address": { type: "string", description: "NFT collection contract address" }, "tokenId": { type: "string", description: "Token ID within the collection. e.g. 1234" }, "chain": { type: "string", description: "Blockchain: ethereum or base. Default: ethereum" } },
    required: ["address","tokenId"],
  },
  {
    name: "nft_metadata",
    description: "NFT metadata lookup -- name, image, attributes, collection info from contract + token ID",
    url: "https://nft-metadata.api.klymax402.com",
    method: "POST",
    path: "/api/metadata",
    price: "$0.003", category: "nft",
    parameters: { "contract": { type: "string", description: "NFT contract address (e.g. 0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D)" }, "tokenId": { type: "string", description: "Token ID within the contract" }, "chain": { type: "string", description: "Blockchain: 'ethereum' or 'base' (default: ethereum)" } },
    required: ["contract","tokenId"],
  },
  {
    name: "solana_launches",
    description: "New token launches on Solana: pump.fun, Raydium",
    url: "https://solana-launches.api.klymax402.com",
    method: "GET",
    path: "/api/launches",
    price: "$0.003", category: "solana",
    parameters: { "limit": { type: "number", description: "Number of results to return (default: 20, max: 50)" }, "minLiquidity": { type: "number", description: "Minimum liquidity in USD to filter tokens (default: 1000)" } },
  },
  {
    name: "jupiter_quotes",
    description: "Jupiter aggregator swap quotes on Solana",
    url: "https://jupiter-quotes.api.klymax402.com",
    method: "GET",
    path: "/api/quote",
    price: "$0.002", category: "solana",
    parameters: { "inputMint": { type: "string", description: "Input token mint address or symbol (SOL, USDC, USDT). e.g. So11111111111111111111111111111111111111112 or SOL" }, "outputMint": { type: "string", description: "Output token mint address or symbol (SOL, USDC, USDT). e.g. EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v or USDC" }, "amount": { type: "string", description: "Amount in raw lamports/smallest unit. e.g. 1000000000 = 1 SOL, 1000000 = 1 USDC" }, "slippage": { type: "number", description: "Slippage tolerance in basis points. Default 50 (0.5%). e.g. 100 = 1%" } },
    required: ["inputMint","outputMint","amount"],
  },
  {
    name: "solana_fees",
    description: "Solana priority fee estimates at 6 levels for transaction optimization",
    url: "https://solana-fees.api.klymax402.com",
    method: "GET",
    path: "/api/fees",
    price: "$0.001", category: "solana",
    parameters: { "program": { type: "string", description: "Program ID to get program-specific fees (e.g. JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4 for Jupiter). Optional — omit for global fees." } },
  },
  {
    name: "solana_pools",
    description: "Solana DEX pool liquidity depth -- TVL, slippage, volume, fee tier for Raydium, Orca, Meteora",
    url: "https://solana-pools.api.klymax402.com",
    method: "GET",
    path: "/api/pool",
    price: "$0.003", category: "solana",
    parameters: { "mint": { type: "string", description: "Solana token mint address to look up pools for (e.g. So11111111111111111111111111111111111111112 for SOL)." } },
    required: ["mint"],
  },
  {
    name: "trust_score",
    description: "Unified trust scoring for domains, wallets, APIs. SSL/DNS/WHOIS/headers. Score 0-100 with risk flags",
    url: "https://trust-score.api.klymax402.com",
    method: "POST",
    path: "/api/score",
    price: "$0.01", category: "security",
    parameters: { "target": { type: "string", description: "Domain (example.com), full URL (https://api.example.com/v1), wallet address (0x...), or IP address to evaluate" }, "checks": { type: "array", description: "Which checks to run. Default: all. Pass a subset like [\"ssl\",\"dns\"] for faster results (under 2s). Full scan takes 3-8s." } },
    required: ["target"],
  },
  {
    name: "token_safety",
    description: "Rug pull detection: honeypot, liquidity lock, ownership renounce, tax analysis",
    url: "https://token-safety.api.klymax402.com",
    method: "GET",
    path: "/api/check",
    price: "$0.003", category: "security",
    parameters: { "address": { type: "string", description: "Token contract address (e.g. 0x...)" }, "chain": { type: "string", description: "Chain to check on: 'ethereum' or 'base' (default: ethereum)" } },
    required: ["address"],
  },
  {
    name: "domain_intelligence",
    description: "DNS, WHOIS, SSL, registrar data for any domain. Full domain intelligence report",
    url: "https://domain-intelligence.api.klymax402.com",
    method: "GET",
    path: "/api/lookup",
    price: "$0.005", category: "security",
    parameters: { "domain": { type: "string", description: "Domain to lookup (e.g. example.com)" } },
    required: ["domain"],
  },
  {
    name: "ssl_checker",
    description: "SSL/TLS certificate validity, expiry, issuer, chain details, and security grade",
    url: "https://ssl-checker.api.klymax402.com",
    method: "POST",
    path: "/api/check",
    price: "$0.002", category: "security",
    parameters: { "domain": { type: "string", description: "Domain name to check SSL certificate (e.g. example.com)" } },
    required: ["domain"],
  },
  {
    name: "http_headers",
    description: "Analyze HTTP response headers -- security score, HSTS/CSP check, server detection, caching config",
    url: "https://http-headers.api.klymax402.com",
    method: "POST",
    path: "/api/analyze",
    price: "$0.001", category: "security",
    parameters: { "url": { type: "string", description: "Full URL to analyze (e.g. https://example.com)" } },
    required: ["url"],
  },
  {
    name: "port_scanner",
    description: "Scan TCP ports on any host -- open/closed status and response time",
    url: "https://port-scanner.api.klymax402.com",
    method: "POST",
    path: "/api/scan",
    price: "$0.003", category: "security",
    parameters: { "host": { type: "string", description: "The hostname or IP address to scan" }, "ports": { type: "array", description: "Array of port numbers to scan (default: [21,22,25,53,80,110,143,443,993,995,3306,3389,5432,6379,8080,8443])" } },
    required: ["host"],
  },
  {
    name: "password_strength",
    description: "Password strength score 0-100, entropy bits, crack time estimate, improvement tips",
    url: "https://password-strength.api.klymax402.com",
    method: "POST",
    path: "/api/check",
    price: "$0.001", category: "security",
    parameters: { "password": { type: "string", description: "The password to analyze" } },
    required: ["password"],
  },
  {
    name: "jwt_decoder",
    description: "Decode and inspect JWT tokens -- header, payload, claims, expiry analysis",
    url: "https://jwt-decoder.api.klymax402.com",
    method: "POST",
    path: "/api/decode",
    price: "$0.001", category: "security",
    parameters: { "token": { type: "string", description: "The JWT token to decode (format: header.payload.signature)" } },
    required: ["token"],
  },
  {
    name: "email_verification",
    description: "Verify email addresses: syntax, MX, disposable, role-based, quality score 0-100",
    url: "https://email-verification.api.klymax402.com",
    method: "POST",
    path: "/api/verify",
    price: "$0.002", category: "enrichment",
    parameters: { "email": { type: "string", description: "Email address to verify (e.g. user@example.com)" } },
    required: ["email"],
  },
  {
    name: "company_enrichment",
    description: "Company data from domain: industry, size, tech stack, social profiles, founded date",
    url: "https://company-enrichment.api.klymax402.com",
    method: "GET",
    path: "/api/enrich",
    price: "$0.01", category: "enrichment",
    parameters: { "domain": { type: "string", description: "Domain to enrich (e.g. stripe.com, shopify.com)" } },
    required: ["domain"],
  },
  {
    name: "person_enrichment",
    description: "Person data from email: name, role, company, social profiles, location",
    url: "https://person-enrichment.api.klymax402.com",
    method: "GET",
    path: "/api/enrich",
    price: "$0.01", category: "enrichment",
    parameters: { "email": { type: "string", description: "Email address to enrich (e.g. john@company.com)" } },
    required: ["email"],
  },
  {
    name: "email_finder",
    description: "Find professional email from name + domain. Pattern matching + verification",
    url: "https://email-finder.api.klymax402.com",
    method: "GET",
    path: "/api/find",
    price: "$0.005", category: "enrichment",
    parameters: { "domain": { type: "string", description: "Company domain (e.g. company.com)" }, "firstName": { type: "string", description: "Person's first name (e.g. John)" }, "lastName": { type: "string", description: "Person's last name (e.g. Doe)" } },
    required: ["domain","firstName","lastName"],
  },
  {
    name: "tech_enrichment",
    description: "Detect 50+ technologies on any website -- CMS, JS frameworks, analytics, hosting, CDN, payments",
    url: "https://tech-enrichment.api.klymax402.com",
    method: "GET",
    path: "/api/detect",
    price: "$0.005", category: "enrichment",
    parameters: { "url": { type: "string", description: "URL to scan (e.g. https://example.com or example.com)" } },
    required: ["url"],
  },
  {
    name: "social_profile",
    description: "Enrich social profiles from handle or URL -- Twitter/X, GitHub, LinkedIn, YouTube",
    url: "https://social-profile.api.klymax402.com",
    method: "GET",
    path: "/api/lookup",
    price: "$0.008", category: "enrichment",
    parameters: { "handle": { type: "string", description: "Username/handle to lookup (e.g. torvalds)" }, "platform": { type: "string", description: "Platform to search on (github, twitter, linkedin, youtube)", enum: ["github","twitter","linkedin","youtube"] }, "url": { type: "string", description: "Full profile URL (alternative to handle+platform, e.g. https://github.com/torvalds)" } },
  },
  {
    name: "email_deliverability",
    description: "Email deliverability audit -- SPF, DKIM, DMARC, MX validation with score 0-100",
    url: "https://email-deliverability.api.klymax402.com",
    method: "GET",
    path: "/api/audit",
    price: "$0.005", category: "email",
    parameters: { "domain": { type: "string", description: "Domain to audit (e.g. example.com, gmail.com)" } },
    required: ["domain"],
  },
  {
    name: "email_send",
    description: "Send emails programmatically via Resend -- text or HTML, delivery status, message ID",
    url: "https://email-send.api.klymax402.com",
    method: "POST",
    path: "/api/send",
    price: "$0.003", category: "email",
    parameters: { "to": { type: "string", description: "Recipient email address" }, "from": { type: "string", description: "Sender email address (default: noreply@x402.dev)" }, "subject": { type: "string", description: "Email subject line" }, "body": { type: "string", description: "Email body content (plain text)" }, "html": { type: "string", description: "Email body content (HTML, optional — overrides body)" } },
    required: ["to","subject","body"],
  },
  {
    name: "web_scraper",
    description: "Extract clean markdown from any URL. Headless browser rendering. Batch support",
    url: "https://web-scraper.api.klymax402.com",
    method: "GET",
    path: "/api/scrape",
    price: "$0.005", category: "web",
    parameters: { "url": { type: "string", description: "URL to scrape (e.g. https://example.com/article)" } },
    required: ["url"],
  },
  {
    name: "seo_analyzer",
    description: "Complete SEO audit: meta, headings, links, schema, performance. Score 0-100",
    url: "https://seo-analyzer.api.klymax402.com",
    method: "GET",
    path: "/api/audit",
    price: "$0.02", category: "web",
    parameters: { "url": { type: "string", description: "Full URL to audit (e.g. https://example.com)" } },
    required: ["url"],
  },
  {
    name: "screenshot_pdf",
    description: "Capture screenshots (PNG/JPEG/WebP) and generate PDFs from any URL",
    url: "https://screenshot-pdf.api.klymax402.com",
    method: "GET",
    path: "/api/screenshot",
    price: "$0.008", category: "web",
    parameters: { "url": { type: "string", description: "URL to screenshot (e.g. https://example.com)" }, "width": { type: "number", description: "Viewport width in px (default: 1280)" }, "height": { type: "number", description: "Viewport height in px (default: 720)" }, "fullPage": { type: "boolean", description: "Capture full scrollable page (default: false)" }, "format": { type: "string", description: "Image format (default: png)", enum: ["png","jpeg","webp"] } },
    required: ["url"],
  },
  {
    name: "web_search",
    description: "Web search API for AI agents -- structured results: title, URL, snippet, up to 10 results",
    url: "https://web-search.api.klymax402.com",
    method: "POST",
    path: "/api/search",
    price: "$0.003", category: "web",
    parameters: { "query": { type: "string", description: "The search query" }, "count": { type: "number", description: "Number of results to return (default: 5, max: 10)" } },
    required: ["query"],
  },
  {
    name: "keyword_research",
    description: "SEO keyword research -- Google Suggest, intent classification, long-tail discovery",
    url: "https://keyword-research.api.klymax402.com",
    method: "GET",
    path: "/api/keywords",
    price: "$0.01", category: "web",
    parameters: { "query": { type: "string", description: "The seed keyword or phrase to research (e.g. 'bitcoin trading', 'best crm software')" } },
    required: ["query"],
  },
  {
    name: "webhook_tester",
    description: "Test webhook endpoints -- POST/PUT/PATCH/DELETE with custom headers and payloads, latency",
    url: "https://webhook-tester.api.klymax402.com",
    method: "POST",
    path: "/api/test",
    price: "$0.002", category: "web",
    parameters: { "url": { type: "string", description: "Webhook URL to test (must be https)" }, "method": { type: "string", description: "HTTP method: POST, PUT, PATCH, DELETE (default: POST)" }, "headers": { type: "object", description: "Custom headers as key-value pairs" }, "body": { type: "object", description: "JSON body to send" }, "timeout": { type: "number", description: "Timeout in seconds (default: 10, max: 30)" } },
    required: ["url"],
  },
  {
    name: "twitter_scraper",
    description: "Scrape Twitter/X profiles, search tweets, user timelines. No API key needed",
    url: "https://twitter-scraper.api.klymax402.com",
    method: "POST",
    path: "/api/profile",
    price: "$0.005", category: "social",
    parameters: { "username": { type: "string", description: "Twitter/X username without @ (e.g. 'elonmusk') or full URL (e.g. 'https://x.com/elonmusk')" } },
    required: ["username"],
  },
  {
    name: "dns_lookup",
    description: "DNS records (A, AAAA, MX, TXT, CNAME, NS, SOA, SRV) via Cloudflare DNS-over-HTTPS",
    url: "https://dns-lookup.api.klymax402.com",
    method: "POST",
    path: "/api/lookup",
    price: "$0.002", category: "network",
    parameters: { "domain": { type: "string", description: "Domain name to lookup (e.g. example.com)" }, "type": { type: "string", description: "DNS record type: A, AAAA, MX, TXT, CNAME, NS, SOA, SRV (default: A)" } },
    required: ["domain"],
  },
  {
    name: "ip_geolocation",
    description: "Geolocate any IP -- country, city, ISP, ASN, VPN/proxy/Tor detection",
    url: "https://ip-geolocation.api.klymax402.com",
    method: "GET",
    path: "/api/lookup",
    price: "$0.003", category: "network",
    parameters: { "ip": { type: "string", description: "IP address to lookup (e.g. 8.8.8.8)" } },
    required: ["ip"],
  },
  {
    name: "ip_geolocation_batch",
    description: "Geolocate up to 20 IP addresses in one call with full location and network data",
    url: "https://ip-geolocation.api.klymax402.com",
    method: "POST",
    path: "/api/lookup/batch",
    price: "$0.01", category: "network",
    parameters: { "ips": { type: "array", description: "Array of IP addresses to lookup (max 20)" } },
    required: ["ips"],
  },
  {
    name: "ai_summarizer",
    description: "Summarize text or URLs into key bullet points. Powered by Claude Haiku",
    url: "https://ai-summarizer.api.klymax402.com",
    method: "POST",
    path: "/api/summarize",
    price: "$0.01", category: "nlp",
    parameters: { "text": { type: "string", description: "The text to summarize" }, "maxLength": { type: "number", description: "Maximum summary length in words (default 200)" } },
    required: ["text"],
  },
  {
    name: "sentiment_analyzer",
    description: "Analyze text sentiment, emotions, confidence scores",
    url: "https://sentiment-analyzer.api.klymax402.com",
    method: "POST",
    path: "/api/analyze",
    price: "$0.005", category: "nlp",
    parameters: { "text": { type: "string", description: "The text to analyze for sentiment" } },
    required: ["text"],
  },
  {
    name: "text_translator",
    description: "Translate text between 50+ languages with auto-detection",
    url: "https://text-translator.api.klymax402.com",
    method: "POST",
    path: "/api/translate",
    price: "$0.005", category: "nlp",
    parameters: { "text": { type: "string", description: "The text to translate (max 5000 characters)" }, "from": { type: "string", description: "Source language code (e.g. 'en', 'fr', 'de') or 'auto' for detection. Default: 'auto'" }, "to": { type: "string", description: "Target language code (e.g. 'en', 'fr', 'de', 'es', 'it', 'pt', 'zh', 'ja', 'ko', 'ar'). Default: 'en'" } },
    required: ["text"],
  },
  {
    name: "text_classifier",
    description: "Classify text into topic categories with confidence scores, readability, content type detection",
    url: "https://text-classifier.api.klymax402.com",
    method: "POST",
    path: "/api/classify",
    price: "$0.005", category: "nlp",
    parameters: { "text": { type: "string", description: "The text content to classify (min 50 characters for accurate results)" }, "categories": { type: "array", description: "Optional custom categories to classify against. Default: tech, finance, health, sports, politics, entertainment, science, business" } },
    required: ["text"],
  },
  {
    name: "language_detector",
    description: "Detect language from text -- 30+ languages, script detection, confidence scores",
    url: "https://language-detector.api.klymax402.com",
    method: "POST",
    path: "/api/detect",
    price: "$0.002", category: "nlp",
    parameters: { "text": { type: "string", description: "The text to detect language for (min 10 characters for accuracy)" } },
    required: ["text"],
  },
  {
    name: "stock_price",
    description: "Real-time stock quotes: price, change, volume, market cap",
    url: "https://stock-price.api.klymax402.com",
    method: "POST",
    path: "/api/quote",
    price: "$0.002", category: "finance",
    parameters: { "symbol": { type: "string", description: "Stock ticker symbol (e.g. AAPL, TSLA, MSFT, GOOG)" } },
    required: ["symbol"],
  },
  {
    name: "image_resize",
    description: "Resize images from URL -- custom dimensions, format conversion (PNG/JPEG/WebP), aspect ratio preserved",
    url: "https://image-resize.api.klymax402.com",
    method: "POST",
    path: "/api/resize",
    price: "$0.003", category: "media",
    parameters: { "url": { type: "string", description: "URL of the image to resize" }, "width": { type: "number", description: "Target width in pixels (maintains aspect ratio if height is omitted)" }, "height": { type: "number", description: "Target height in pixels (maintains aspect ratio if width is omitted)" }, "format": { type: "string", description: "Output format: 'png', 'jpeg', or 'webp' (default: png)" } },
    required: ["url"],
  },
  {
    name: "ocr_extract",
    description: "Extract text from images via OCR -- URL or base64, confidence score, language detection",
    url: "https://ocr-extract.api.klymax402.com",
    method: "POST",
    path: "/api/ocr",
    price: "$0.005", category: "media",
    parameters: { "image_url": { type: "string", description: "URL of the image to extract text from" }, "image_base64": { type: "string", description: "Base64-encoded image data (alternative to image_url)" }, "language": { type: "string", description: "Language hint for OCR: eng, fra, deu, spa, etc. (default: eng)" } },
  },
  {
    name: "text_to_speech",
    description: "Convert text to speech -- 20+ languages, base64 MP3 output",
    url: "https://text-to-speech.api.klymax402.com",
    method: "POST",
    path: "/api/speak",
    price: "$0.005", category: "media",
    parameters: { "text": { type: "string", description: "The text to convert to speech (max 200 characters per request)" }, "language": { type: "string", description: "Language code: en, fr, es, de, it, pt, ja, ko, zh, ar, ru, hi, etc. (default: en)" } },
    required: ["text"],
  },
  {
    name: "diff_checker",
    description: "Compare two texts line-by-line with additions, deletions, similarity score",
    url: "https://diff-checker.api.klymax402.com",
    method: "POST",
    path: "/api/diff",
    price: "$0.002", category: "text",
    parameters: { "text1": { type: "string", description: "The original text (base)" }, "text2": { type: "string", description: "The modified text to compare against" } },
    required: ["text1","text2"],
  },
  {
    name: "word_counter",
    description: "Text metrics: words, characters, sentences, paragraphs, reading time",
    url: "https://word-counter.api.klymax402.com",
    method: "POST",
    path: "/api/count",
    price: "$0.001", category: "text",
    parameters: { "text": { type: "string", description: "The text to analyze" } },
    required: ["text"],
  },
  {
    name: "lorem_ipsum",
    description: "Generate Lorem Ipsum placeholder text -- paragraphs, sentences, or words",
    url: "https://lorem-ipsum.api.klymax402.com",
    method: "POST",
    path: "/api/generate",
    price: "$0.001", category: "text",
    parameters: { "count": { type: "number", description: "Number of paragraphs, sentences, or words to generate (default: 3)" }, "type": { type: "string", description: "Type of text to generate: paragraphs, sentences, or words (default: paragraphs)" } },
    required: ["count","type"],
  },
  {
    name: "slug_generator",
    description: "Convert text to clean URL-friendly slugs with transliteration",
    url: "https://slug-generator.api.klymax402.com",
    method: "POST",
    path: "/api/slugify",
    price: "$0.001", category: "text",
    parameters: { "text": { type: "string", description: "The text to convert into a slug" }, "separator": { type: "string", description: "Character to use as word separator (default: -)" }, "lowercase": { type: "boolean", description: "Convert to lowercase (default: true)" } },
    required: ["text"],
  },
  {
    name: "regex_tester",
    description: "Test regex patterns -- matches, capture groups, positions, pattern explanations",
    url: "https://regex-generator.api.klymax402.com",
    method: "POST",
    path: "/api/test",
    price: "$0.001", category: "text",
    parameters: { "pattern": { type: "string", description: "Regular expression pattern (without delimiters)" }, "flags": { type: "string", description: "Regex flags: g, i, m, s, u (default: g)" }, "testStrings": { type: "array", description: "Array of strings to test against the pattern" } },
    required: ["pattern","testStrings"],
  },
  {
    name: "html_to_markdown",
    description: "Convert HTML to clean Markdown -- preserves headings, links, lists, images",
    url: "https://html-to-markdown.api.klymax402.com",
    method: "POST",
    path: "/api/convert",
    price: "$0.001", category: "text",
    parameters: { "html": { type: "string", description: "HTML content to convert to markdown" } },
    required: ["html"],
  },
  {
    name: "markdown_to_html",
    description: "Convert Markdown to HTML -- headings, lists, code blocks, tables, links",
    url: "https://markdown-to-html.api.klymax402.com",
    method: "POST",
    path: "/api/convert",
    price: "$0.001", category: "text",
    parameters: { "markdown": { type: "string", description: "Markdown text to convert" }, "wrapInDocument": { type: "boolean", description: "Wrap output in full HTML document (default: false)" } },
    required: ["markdown"],
  },
  {
    name: "markdown_renderer",
    description: "Render Markdown to styled HTML with CSS themes -- light, dark, GitHub",
    url: "https://markdown-renderer.api.klymax402.com",
    method: "POST",
    path: "/api/render",
    price: "$0.002", category: "text",
    parameters: { "markdown": { type: "string", description: "Markdown text to render" }, "theme": { type: "string", description: "CSS theme: 'light', 'dark', or 'github' (default: github)" } },
    required: ["markdown"],
  },
  {
    name: "fact_checker",
    description: "Verify factual claims with web evidence, source URLs, and confidence assessment",
    url: "https://fact-checker.api.klymax402.com",
    method: "POST",
    path: "/api/check",
    price: "$0.005", category: "research",
    parameters: { "claim": { type: "string", description: "The factual claim to verify (e.g., 'The Eiffel Tower is 330 meters tall')" }, "max_sources": { type: "number", description: "Maximum number of sources to return (default: 5, max: 10)" } },
    required: ["claim"],
  },
  {
    name: "research_report",
    description: "Multi-source research reports on any topic -- structured markdown, findings, sources",
    url: "https://research-report.api.klymax402.com",
    method: "POST",
    path: "/api/report",
    price: "$0.02", category: "research",
    parameters: { "topic": { type: "string", description: "The research topic to investigate" }, "depth": { type: "string", description: "Research depth: quick (3 sources), standard (5 sources), deep (8 sources). Default: standard" } },
    required: ["topic"],
  },
  {
    name: "gdpr_scanner",
    description: "Scan website GDPR compliance: consent, privacy, trackers. Score 0-100",
    url: "https://gdpr-scanner.api.klymax402.com",
    method: "GET",
    path: "/api/scan",
    price: "$0.02", category: "compliance",
    parameters: { "url": { type: "string", description: "Website URL to scan for GDPR compliance (e.g. https://example.com)" } },
    required: ["url"],
  },
  {
    name: "pii_detector",
    description: "Detect PII in text -- emails, phones, SSNs, credit cards, IPs with risk scoring and redaction",
    url: "https://pii-detector.api.klymax402.com",
    method: "POST",
    path: "/api/detect",
    price: "$0.005", category: "compliance",
    parameters: { "text": { type: "string", description: "Text content to scan for PII" } },
    required: ["text"],
  },
  {
    name: "phone_validation",
    description: "Validate phone numbers worldwide: carrier, line type, country, E.164 format",
    url: "https://phone-validation.api.klymax402.com",
    method: "GET",
    path: "/api/validate",
    price: "$0.003", category: "validation",
    parameters: { "phone": { type: "string", description: "Phone number to validate (e.g. +33612345678, +14155552671, 0033612345678)" } },
    required: ["phone"],
  },
  {
    name: "phone_validation_batch",
    description: "Validate up to 50 phone numbers in a single batch request",
    url: "https://phone-validation.api.klymax402.com",
    method: "POST",
    path: "/api/validate/batch",
    price: "$0.025", category: "validation",
    parameters: { "phones": { type: "array", description: "Array of phone numbers to validate (max 50)" } },
    required: ["phones"],
  },
  {
    name: "sms_validator",
    description: "Validate if a phone number can receive SMS with carrier type and E.164 format",
    url: "https://sms-validator.api.klymax402.com",
    method: "POST",
    path: "/api/validate",
    price: "$0.002", category: "validation",
    parameters: { "phone": { type: "string", description: "Phone number with country code (e.g. +14155551234)" }, "countryCode": { type: "string", description: "ISO 3166-1 alpha-2 country code hint (e.g. US, FR, GB)" } },
    required: ["phone"],
  },
  {
    name: "address_validator",
    description: "Parse, validate, normalize postal addresses with country detection",
    url: "https://address-validator.api.klymax402.com",
    method: "POST",
    path: "/api/validate",
    price: "$0.003", category: "validation",
    parameters: { "address": { type: "string", description: "Full address string to parse and validate (e.g. '123 Main St, New York, NY 10001')" } },
    required: ["address"],
  },
  {
    name: "json_validator",
    description: "Validate JSON syntax and check against JSON Schema with structure stats",
    url: "https://json-validator.api.klymax402.com",
    method: "POST",
    path: "/api/validate",
    price: "$0.001", category: "validation",
    parameters: { "json": { type: "string", description: "JSON string to validate" }, "schema": { type: "object", description: "Optional JSON Schema to validate against" } },
    required: ["json"],
  },
  {
    name: "code_sandbox",
    description: "Execute Python, JavaScript, or SQL in a sandbox with stdout, execution time, errors",
    url: "https://code-sandbox.api.klymax402.com",
    method: "POST",
    path: "/api/execute",
    price: "$0.01", category: "developer",
    parameters: { "code": { type: "string", description: "The code to execute" }, "language": { type: "string", description: "Programming language: python, javascript, or sql", enum: ["python","javascript","sql"] }, "timeout": { type: "number", description: "Execution timeout in milliseconds (default: 5000, max: 10000)" } },
    required: ["code","language"],
  },
  {
    name: "qr_code",
    description: "Generate QR codes from text or URLs -- base64 PNG output, configurable size",
    url: "https://qr-code.api.klymax402.com",
    method: "POST",
    path: "/api/qr",
    price: "$0.001", category: "generator",
    parameters: { "data": { type: "string", description: "The text or URL to encode in the QR code" }, "size": { type: "number", description: "QR code size in modules (default: 21 for version 1)" } },
    required: ["data"],
  },
  {
    name: "barcode_generator",
    description: "Generate barcodes -- EAN-13, UPC-A, Code128, Code39 as base64 SVG",
    url: "https://barcode-generator.api.klymax402.com",
    method: "POST",
    path: "/api/barcode",
    price: "$0.001", category: "generator",
    parameters: { "data": { type: "string", description: "Data to encode in the barcode" }, "format": { type: "string", description: "Barcode format: code128, code39, ean13, upca (default: code128)" }, "width": { type: "number", description: "Bar width in pixels (default: 2)" }, "height": { type: "number", description: "Barcode height in pixels (default: 100)" } },
    required: ["data"],
  },
  {
    name: "hash_generator",
    description: "Generate MD5, SHA1, SHA256, SHA512, and bcrypt hashes",
    url: "https://hash-generator.api.klymax402.com",
    method: "POST",
    path: "/api/hash",
    price: "$0.001", category: "generator",
    parameters: { "text": { type: "string", description: "The text to hash" }, "algorithm": { type: "string", description: "Hash algorithm: md5, sha1, sha256, sha512, bcrypt (default: sha256)" } },
    required: ["text"],
  },
  {
    name: "uuid_generator",
    description: "Generate UUID v4, v7, ULID, or nanoid identifiers -- batch up to 100",
    url: "https://uuid-generator.api.klymax402.com",
    method: "POST",
    path: "/api/generate",
    price: "$0.001", category: "generator",
    parameters: { "format": { type: "string", description: "Format: uuidv4, uuidv7, ulid, nanoid (default: uuidv4)" }, "count": { type: "number", description: "Number to generate (default: 1, max: 100)" }, "length": { type: "number", description: "Length for nanoid (default: 21)" } },
  },
  {
    name: "color_palette",
    description: "Generate harmonious color palettes from hex -- 5 schemes, hex/RGB/HSL/CSS vars",
    url: "https://color-palette.api.klymax402.com",
    method: "POST",
    path: "/api/palette",
    price: "$0.001", category: "generator",
    parameters: { "color": { type: "string", description: "Base hex color (e.g. #FF5733 or FF5733)" }, "scheme": { type: "string", description: "Color scheme: complementary, analogous, triadic, split-complementary, tetradic (default: complementary)" }, "count": { type: "number", description: "Number of colors to generate (default: 5, max: 10)" } },
    required: ["color"],
  },
  {
    name: "pdf_generator",
    description: "Generate PDF from HTML or Markdown with custom page size, margins, headers",
    url: "https://pdf-generator.api.klymax402.com",
    method: "POST",
    path: "/api/generate",
    price: "$0.008", category: "document",
    parameters: { "content": { type: "string", description: "HTML or Markdown content to convert to PDF" }, "format": { type: "string", description: "Content format: html or markdown (default: html)", enum: ["html","markdown"] }, "pageSize": { type: "string", description: "Page size: A4, Letter, or Legal (default: A4)", enum: ["A4","Letter","Legal"] }, "landscape": { type: "boolean", description: "Landscape orientation (default: false)" }, "margins": { type: "object", description: "Custom margins (default: 20mm all sides)" } },
    required: ["content"],
  },
  {
    name: "base64_codec",
    description: "Encode/decode base64 with standard and URL-safe variants",
    url: "https://base64-codec.api.klymax402.com",
    method: "POST",
    path: "/api/encode",
    price: "$0.001", category: "utility",
    parameters: { "data": { type: "string", description: "The data to encode or decode" }, "action": { type: "string", description: "Action: 'encode' or 'decode' (default: encode)" } },
    required: ["data"],
  },
  {
    name: "csv_to_json",
    description: "Parse CSV to JSON array -- auto-detect delimiter, header row support",
    url: "https://csv-to-json.api.klymax402.com",
    method: "POST",
    path: "/api/parse",
    price: "$0.001", category: "utility",
    parameters: { "csv": { type: "string", description: "CSV content to parse" }, "delimiter": { type: "string", description: "Delimiter: comma, semicolon, tab, pipe (default: auto-detect)" }, "hasHeaders": { type: "boolean", description: "First row is headers (default: true)" } },
    required: ["csv"],
  },
  {
    name: "cron_parser",
    description: "Parse, validate, explain cron expressions with next N run times in any timezone",
    url: "https://cron-parser.api.klymax402.com",
    method: "POST",
    path: "/api/parse",
    price: "$0.001", category: "utility",
    parameters: { "expression": { type: "string", description: "Cron expression (e.g. '0 9 * * 1-5' or '*/5 * * * *')" }, "timezone": { type: "string", description: "IANA timezone (default: UTC, e.g. America/New_York)" }, "count": { type: "number", description: "Number of next run times to return (default: 5, max: 20)" } },
    required: ["expression"],
  },
  {
    name: "crontab_generator",
    description: "Natural language to cron -- 'every Monday at 9am' to valid cron expression",
    url: "https://crontab-generator.api.klymax402.com",
    method: "POST",
    path: "/api/generate",
    price: "$0.001", category: "utility",
    parameters: { "description": { type: "string", description: "Natural language description of the schedule (e.g. 'every Monday at 9am', 'twice a day', 'every 5 minutes')" } },
    required: ["description"],
  },
  {
    name: "timezone_converter",
    description: "Convert datetime between timezones -- all IANA zones, UTC offset, DST-aware",
    url: "https://timezone-converter.api.klymax402.com",
    method: "POST",
    path: "/api/convert",
    price: "$0.001", category: "utility",
    parameters: { "datetime": { type: "string", description: "Date/time string (ISO 8601 or human-readable, e.g. '2024-01-15T14:30:00')" }, "from": { type: "string", description: "Source IANA timezone (e.g. America/New_York)" }, "to": { type: "string", description: "Target IANA timezone (e.g. Europe/Paris)" } },
    required: ["datetime","from","to"],
  },
  {
    name: "unit_converter",
    description: "Convert units -- length, weight, temperature, volume, speed, data storage",
    url: "https://unit-converter.api.klymax402.com",
    method: "POST",
    path: "/api/convert",
    price: "$0.001", category: "utility",
    parameters: { "value": { type: "number", description: "The numeric value to convert" }, "from": { type: "string", description: "Source unit (e.g. km, lb, celsius, l, mph, MB)" }, "to": { type: "string", description: "Target unit (e.g. mi, kg, fahrenheit, gal, km/h, GB)" }, "category": { type: "string", description: "Optional category hint: length, weight, temperature, volume, speed, data" } },
    required: ["value","from","to"],
  },
  {
    name: "url_shortener",
    description: "Shorten URLs -- hash-based, custom alias support",
    url: "https://url-shortener.api.klymax402.com",
    method: "POST",
    path: "/api/shorten",
    price: "$0.001", category: "utility",
    parameters: { "url": { type: "string", description: "The URL to shorten" }, "custom_alias": { type: "string", description: "Optional custom alias for the short URL (3-20 alphanumeric chars)" } },
    required: ["url"],
  },
  {
    name: "user_agent_parser",
    description: "Parse user agent strings -- browser, OS, device type, engine, bot detection",
    url: "https://user-agent-parser.api.klymax402.com",
    method: "POST",
    path: "/api/parse",
    price: "$0.001", category: "utility",
    parameters: { "userAgent": { type: "string", description: "The user agent string to parse" } },
    required: ["userAgent"],
  },
  {
    name: "weather",
    description: "Current weather and 7-day forecast -- temperature, humidity, wind, precipitation",
    url: "https://weather-api.api.klymax402.com",
    method: "POST",
    path: "/api/weather",
    price: "$0.001", category: "data",
    parameters: { "latitude": { type: "number", description: "Latitude (-90 to 90)" }, "longitude": { type: "number", description: "Longitude (-180 to 180)" }, "city": { type: "string", description: "City name (alternative to lat/lon, uses geocoding)" } },
  },
  {
    name: "vector_search",
    description: "In-memory vector store with TF-IDF and cosine similarity for document retrieval",
    url: "https://vector-search.api.klymax402.com",
    method: "POST",
    path: "/api/search",
    price: "$0.005", category: "data",
    parameters: { "documents": { type: "array", description: "Array of text documents to index (optional if already stored in this session)" }, "query": { type: "string", description: "The text query to search for" }, "topK": { type: "number", description: "Number of top results to return (default: 3, max: 10)" }, "namespace": { type: "string", description: "Namespace to isolate document sets (default: 'default')" } },
    required: ["query"],
  },
];

export const CATEGORIES = [...new Set(CATALOG.map((t) => t.category))];

export function getToolsByCategory(category: string): ApiTool[] {
  return CATALOG.filter((t) => t.category === category);
}

export function getTool(name: string): ApiTool | undefined {
  return CATALOG.find((t) => t.name === name);
}
